### PR TITLE
Move v1 tree from metafeeds spec

### PR DESCRIPTION
**Pull request by arj03**
This is basically just moving over the v1 part of the spec from https://github.com/ssbc/ssb-meta-feeds-spec to streamline that spec and keep specific information in this repo.

### CODE REVIEW

**Review by mixmix — APPROVED** [review]
NICE

**Comment by staltz** [comment]
Hmm, in my opinion the v1 tree structure is a spec, it's like a spec that depends on the metafeed "core" spec. v1 tree structure isn't IMO a migration guide. It might be confusing people to put it here.

**Comment by arj03** [comment]
I can move it back to the meta feeds spec and just link it here like before. Well have to update the other PR. There is the key mangement section that is also somewhat migration specific.

**Comment by staltz** [comment]
What's the "key management" section?

**Comment by arj03** [comment]
From this branch https://github.com/ssbc/ssb-meta-feeds-spec/tree/rework#key-management

**Comment by staltz** [comment]
Ah, right! Completely agree it belongs to migration doc.

**Pull request closed without merging**
